name: Snyk Code Security Scan

on:
  push:
    branches: ["main", "vitoria-snyk-target-branch" ]
  pull_request:
    branches: ["main", "vitoria-snyk-target-branch"]

permissions:
  contents: read
  security-events: write

jobs:
  snyk_security_analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Run Snyk Analysis and Report to both platforms
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk code test --report --sarif-file-output=snyk-code.sarif --org=vitoria-isabela --project-name=${{ github.repository }}

      - name: Upload results to GitHub Security
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-code.sarif