name: Snyk Security Scan

on:
  push:
    branches: ["main", "vitoria-snyk-target-branch", "vitoria-snyk-source-branch"]
  pull_request:
    branches: ["main", "vitoria-snyk-target-branch"]

permissions:
  contents: read
  security-events: write

jobs:
  snyk_full_analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Run Snyk Code Scan (for GitHub Security)
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true
        run: |
          snyk code test \
            --sarif-file-output=snyk-code.sarif \
            --org=vitoria-isabela

      - name: Upload SAST results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-code.sarif
      
      - name: Run Snyk Scan and Monitor (for Snyk.io Dashboard)
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true
        run: |
          # O 'snyk test' encontra vulnerabilidades em pacotes (SCA)
          snyk test --all-projects --org=vitoria-isabela
          # O 'snyk monitor' envia os resultados de SCA e SAST para o Snyk.io
          snyk monitor --all-projects --org=vitoria-isabela